// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WordApp.Data;

#nullable disable

namespace WordApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250528071323_ReduceSeedWordsTo20")]
    partial class ReduceSeedWordsTo20
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WordApp.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WordApp.Models.Word", b =>
                {
                    b.Property<int>("WordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WordID"), 1L, 1);

                    b.Property<int>("CorrectStreak")
                        .HasColumnType("int");

                    b.Property<string>("EngWordName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsKnown")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastCorrectDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RepeatCount")
                        .HasColumnType("int");

                    b.Property<string>("TurWordName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("WordID");

                    b.ToTable("Words");

                    b.HasData(
                        new
                        {
                            WordID = -1,
                            CorrectStreak = 0,
                            EngWordName = "apple",
                            IsKnown = false,
                            Picture = "C:/words/apple.jpg",
                            RepeatCount = 0,
                            TurWordName = "elma"
                        },
                        new
                        {
                            WordID = -2,
                            CorrectStreak = 0,
                            EngWordName = "book",
                            IsKnown = false,
                            Picture = "C:/words/book.jpg",
                            RepeatCount = 0,
                            TurWordName = "kitap"
                        },
                        new
                        {
                            WordID = -3,
                            CorrectStreak = 0,
                            EngWordName = "cat",
                            IsKnown = false,
                            Picture = "C:/words/cat.jpg",
                            RepeatCount = 0,
                            TurWordName = "kedi"
                        },
                        new
                        {
                            WordID = -4,
                            CorrectStreak = 0,
                            EngWordName = "dog",
                            IsKnown = false,
                            Picture = "C:/words/dog.jpg",
                            RepeatCount = 0,
                            TurWordName = "köpek"
                        },
                        new
                        {
                            WordID = -5,
                            CorrectStreak = 0,
                            EngWordName = "car",
                            IsKnown = false,
                            Picture = "C:/words/car.jpg",
                            RepeatCount = 0,
                            TurWordName = "araba"
                        },
                        new
                        {
                            WordID = -6,
                            CorrectStreak = 0,
                            EngWordName = "house",
                            IsKnown = false,
                            Picture = "C:/words/house.jpg",
                            RepeatCount = 0,
                            TurWordName = "ev"
                        },
                        new
                        {
                            WordID = -7,
                            CorrectStreak = 0,
                            EngWordName = "tree",
                            IsKnown = false,
                            Picture = "C:/words/tree.jpg",
                            RepeatCount = 0,
                            TurWordName = "ağaç"
                        },
                        new
                        {
                            WordID = -8,
                            CorrectStreak = 0,
                            EngWordName = "water",
                            IsKnown = false,
                            Picture = "C:/words/water.jpg",
                            RepeatCount = 0,
                            TurWordName = "su"
                        },
                        new
                        {
                            WordID = -9,
                            CorrectStreak = 0,
                            EngWordName = "sun",
                            IsKnown = false,
                            Picture = "C:/words/sun.jpg",
                            RepeatCount = 0,
                            TurWordName = "güneş"
                        },
                        new
                        {
                            WordID = -10,
                            CorrectStreak = 0,
                            EngWordName = "moon",
                            IsKnown = false,
                            Picture = "C:/words/moon.jpg",
                            RepeatCount = 0,
                            TurWordName = "ay"
                        },
                        new
                        {
                            WordID = -11,
                            CorrectStreak = 0,
                            EngWordName = "star",
                            IsKnown = false,
                            Picture = "C:/words/star.jpg",
                            RepeatCount = 0,
                            TurWordName = "yıldız"
                        },
                        new
                        {
                            WordID = -12,
                            CorrectStreak = 0,
                            EngWordName = "phone",
                            IsKnown = false,
                            Picture = "C:/words/phone.jpg",
                            RepeatCount = 0,
                            TurWordName = "telefon"
                        },
                        new
                        {
                            WordID = -13,
                            CorrectStreak = 0,
                            EngWordName = "computer",
                            IsKnown = false,
                            Picture = "C:/words/computer.jpg",
                            RepeatCount = 0,
                            TurWordName = "bilgisayar"
                        },
                        new
                        {
                            WordID = -14,
                            CorrectStreak = 0,
                            EngWordName = "table",
                            IsKnown = false,
                            Picture = "C:/words/table.jpg",
                            RepeatCount = 0,
                            TurWordName = "masa"
                        },
                        new
                        {
                            WordID = -15,
                            CorrectStreak = 0,
                            EngWordName = "chair",
                            IsKnown = false,
                            Picture = "C:/words/chair.jpg",
                            RepeatCount = 0,
                            TurWordName = "sandalye"
                        },
                        new
                        {
                            WordID = -16,
                            CorrectStreak = 0,
                            EngWordName = "window",
                            IsKnown = false,
                            Picture = "C:/words/window.jpg",
                            RepeatCount = 0,
                            TurWordName = "pencere"
                        },
                        new
                        {
                            WordID = -17,
                            CorrectStreak = 0,
                            EngWordName = "door",
                            IsKnown = false,
                            Picture = "C:/words/door.jpg",
                            RepeatCount = 0,
                            TurWordName = "kapı"
                        },
                        new
                        {
                            WordID = -18,
                            CorrectStreak = 0,
                            EngWordName = "pen",
                            IsKnown = false,
                            Picture = "C:/words/pen.jpg",
                            RepeatCount = 0,
                            TurWordName = "kalem"
                        },
                        new
                        {
                            WordID = -19,
                            CorrectStreak = 0,
                            EngWordName = "pencil",
                            IsKnown = false,
                            Picture = "C:/words/pencil.jpg",
                            RepeatCount = 0,
                            TurWordName = "kurşun kalem"
                        },
                        new
                        {
                            WordID = -20,
                            CorrectStreak = 0,
                            EngWordName = "notebook",
                            IsKnown = false,
                            Picture = "C:/words/notebook.jpg",
                            RepeatCount = 0,
                            TurWordName = "defter"
                        });
                });

            modelBuilder.Entity("WordApp.Models.WordSample", b =>
                {
                    b.Property<int>("WordSampleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WordSampleId"), 1L, 1);

                    b.Property<string>("Samples")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WordID")
                        .HasColumnType("int");

                    b.HasKey("WordSampleId");

                    b.HasIndex("WordID");

                    b.ToTable("WordSamples");
                });

            modelBuilder.Entity("WordApp.Models.WordSample", b =>
                {
                    b.HasOne("WordApp.Models.Word", "Word")
                        .WithMany("WordSamples")
                        .HasForeignKey("WordID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Word");
                });

            modelBuilder.Entity("WordApp.Models.Word", b =>
                {
                    b.Navigation("WordSamples");
                });
#pragma warning restore 612, 618
        }
    }
}
