// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WordApp.Data;

#nullable disable

namespace WordApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250527165520_AddQuizColumns")]
    partial class AddQuizColumns
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WordApp.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WordApp.Models.Word", b =>
                {
                    b.Property<int>("WordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WordID"), 1L, 1);

                    b.Property<int>("CorrectStreak")
                        .HasColumnType("int");

                    b.Property<string>("EngWordName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsKnown")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastCorrectDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RepeatCount")
                        .HasColumnType("int");

                    b.Property<string>("TurWordName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("WordID");

                    b.ToTable("Words");

                    b.HasData(
                        new
                        {
                            WordID = 1,
                            CorrectStreak = 0,
                            EngWordName = "apple",
                            IsKnown = false,
                            Picture = "C:/words/apple.jpg",
                            RepeatCount = 0,
                            TurWordName = "elma"
                        },
                        new
                        {
                            WordID = 2,
                            CorrectStreak = 0,
                            EngWordName = "book",
                            IsKnown = false,
                            Picture = "C:/words/book.jpg",
                            RepeatCount = 0,
                            TurWordName = "kitap"
                        },
                        new
                        {
                            WordID = 3,
                            CorrectStreak = 0,
                            EngWordName = "cat",
                            IsKnown = false,
                            Picture = "C:/words/cat.jpg",
                            RepeatCount = 0,
                            TurWordName = "kedi"
                        },
                        new
                        {
                            WordID = 4,
                            CorrectStreak = 0,
                            EngWordName = "dog",
                            IsKnown = false,
                            Picture = "C:/words/dog.jpg",
                            RepeatCount = 0,
                            TurWordName = "köpek"
                        },
                        new
                        {
                            WordID = 5,
                            CorrectStreak = 0,
                            EngWordName = "car",
                            IsKnown = false,
                            Picture = "C:/words/car.jpg",
                            RepeatCount = 0,
                            TurWordName = "araba"
                        },
                        new
                        {
                            WordID = 6,
                            CorrectStreak = 0,
                            EngWordName = "house",
                            IsKnown = false,
                            Picture = "C:/words/house.jpg",
                            RepeatCount = 0,
                            TurWordName = "ev"
                        },
                        new
                        {
                            WordID = 7,
                            CorrectStreak = 0,
                            EngWordName = "tree",
                            IsKnown = false,
                            Picture = "C:/words/tree.jpg",
                            RepeatCount = 0,
                            TurWordName = "ağaç"
                        },
                        new
                        {
                            WordID = 8,
                            CorrectStreak = 0,
                            EngWordName = "water",
                            IsKnown = false,
                            Picture = "C:/words/water.jpg",
                            RepeatCount = 0,
                            TurWordName = "su"
                        },
                        new
                        {
                            WordID = 9,
                            CorrectStreak = 0,
                            EngWordName = "sun",
                            IsKnown = false,
                            Picture = "C:/words/sun.jpg",
                            RepeatCount = 0,
                            TurWordName = "güneş"
                        },
                        new
                        {
                            WordID = 10,
                            CorrectStreak = 0,
                            EngWordName = "moon",
                            IsKnown = false,
                            Picture = "C:/words/moon.jpg",
                            RepeatCount = 0,
                            TurWordName = "ay"
                        },
                        new
                        {
                            WordID = 11,
                            CorrectStreak = 0,
                            EngWordName = "star",
                            IsKnown = false,
                            Picture = "C:/words/star.jpg",
                            RepeatCount = 0,
                            TurWordName = "yıldız"
                        },
                        new
                        {
                            WordID = 12,
                            CorrectStreak = 0,
                            EngWordName = "phone",
                            IsKnown = false,
                            Picture = "C:/words/phone.jpg",
                            RepeatCount = 0,
                            TurWordName = "telefon"
                        },
                        new
                        {
                            WordID = 13,
                            CorrectStreak = 0,
                            EngWordName = "computer",
                            IsKnown = false,
                            Picture = "C:/words/computer.jpg",
                            RepeatCount = 0,
                            TurWordName = "bilgisayar"
                        },
                        new
                        {
                            WordID = 14,
                            CorrectStreak = 0,
                            EngWordName = "table",
                            IsKnown = false,
                            Picture = "C:/words/table.jpg",
                            RepeatCount = 0,
                            TurWordName = "masa"
                        },
                        new
                        {
                            WordID = 15,
                            CorrectStreak = 0,
                            EngWordName = "chair",
                            IsKnown = false,
                            Picture = "C:/words/chair.jpg",
                            RepeatCount = 0,
                            TurWordName = "sandalye"
                        },
                        new
                        {
                            WordID = 16,
                            CorrectStreak = 0,
                            EngWordName = "window",
                            IsKnown = false,
                            Picture = "C:/words/window.jpg",
                            RepeatCount = 0,
                            TurWordName = "pencere"
                        },
                        new
                        {
                            WordID = 17,
                            CorrectStreak = 0,
                            EngWordName = "door",
                            IsKnown = false,
                            Picture = "C:/words/door.jpg",
                            RepeatCount = 0,
                            TurWordName = "kapı"
                        },
                        new
                        {
                            WordID = 18,
                            CorrectStreak = 0,
                            EngWordName = "pen",
                            IsKnown = false,
                            Picture = "C:/words/pen.jpg",
                            RepeatCount = 0,
                            TurWordName = "kalem"
                        },
                        new
                        {
                            WordID = 19,
                            CorrectStreak = 0,
                            EngWordName = "pencil",
                            IsKnown = false,
                            Picture = "C:/words/pencil.jpg",
                            RepeatCount = 0,
                            TurWordName = "kurşun kalem"
                        },
                        new
                        {
                            WordID = 20,
                            CorrectStreak = 0,
                            EngWordName = "notebook",
                            IsKnown = false,
                            Picture = "C:/words/notebook.jpg",
                            RepeatCount = 0,
                            TurWordName = "defter"
                        },
                        new
                        {
                            WordID = 21,
                            CorrectStreak = 0,
                            EngWordName = "bag",
                            IsKnown = false,
                            Picture = "C:/words/bag.jpg",
                            RepeatCount = 0,
                            TurWordName = "çanta"
                        },
                        new
                        {
                            WordID = 22,
                            CorrectStreak = 0,
                            EngWordName = "shoe",
                            IsKnown = false,
                            Picture = "C:/words/shoe.jpg",
                            RepeatCount = 0,
                            TurWordName = "ayakkabı"
                        },
                        new
                        {
                            WordID = 23,
                            CorrectStreak = 0,
                            EngWordName = "shirt",
                            IsKnown = false,
                            Picture = "C:/words/shirt.jpg",
                            RepeatCount = 0,
                            TurWordName = "gömlek"
                        },
                        new
                        {
                            WordID = 24,
                            CorrectStreak = 0,
                            EngWordName = "pants",
                            IsKnown = false,
                            Picture = "C:/words/pants.jpg",
                            RepeatCount = 0,
                            TurWordName = "pantolon"
                        },
                        new
                        {
                            WordID = 25,
                            CorrectStreak = 0,
                            EngWordName = "hat",
                            IsKnown = false,
                            Picture = "C:/words/hat.jpg",
                            RepeatCount = 0,
                            TurWordName = "şapka"
                        },
                        new
                        {
                            WordID = 26,
                            CorrectStreak = 0,
                            EngWordName = "clock",
                            IsKnown = false,
                            Picture = "C:/words/clock.jpg",
                            RepeatCount = 0,
                            TurWordName = "saat"
                        },
                        new
                        {
                            WordID = 27,
                            CorrectStreak = 0,
                            EngWordName = "watch",
                            IsKnown = false,
                            Picture = "C:/words/watch.jpg",
                            RepeatCount = 0,
                            TurWordName = "kol saati"
                        },
                        new
                        {
                            WordID = 28,
                            CorrectStreak = 0,
                            EngWordName = "milk",
                            IsKnown = false,
                            Picture = "C:/words/milk.jpg",
                            RepeatCount = 0,
                            TurWordName = "süt"
                        },
                        new
                        {
                            WordID = 29,
                            CorrectStreak = 0,
                            EngWordName = "bread",
                            IsKnown = false,
                            Picture = "C:/words/bread.jpg",
                            RepeatCount = 0,
                            TurWordName = "ekmek"
                        },
                        new
                        {
                            WordID = 30,
                            CorrectStreak = 0,
                            EngWordName = "cheese",
                            IsKnown = false,
                            Picture = "C:/words/cheese.jpg",
                            RepeatCount = 0,
                            TurWordName = "peynir"
                        },
                        new
                        {
                            WordID = 31,
                            CorrectStreak = 0,
                            EngWordName = "egg",
                            IsKnown = false,
                            Picture = "C:/words/egg.jpg",
                            RepeatCount = 0,
                            TurWordName = "yumurta"
                        },
                        new
                        {
                            WordID = 32,
                            CorrectStreak = 0,
                            EngWordName = "butter",
                            IsKnown = false,
                            Picture = "C:/words/butter.jpg",
                            RepeatCount = 0,
                            TurWordName = "tereyağı"
                        },
                        new
                        {
                            WordID = 33,
                            CorrectStreak = 0,
                            EngWordName = "salt",
                            IsKnown = false,
                            Picture = "C:/words/salt.jpg",
                            RepeatCount = 0,
                            TurWordName = "tuz"
                        },
                        new
                        {
                            WordID = 34,
                            CorrectStreak = 0,
                            EngWordName = "sugar",
                            IsKnown = false,
                            Picture = "C:/words/sugar.jpg",
                            RepeatCount = 0,
                            TurWordName = "şeker"
                        },
                        new
                        {
                            WordID = 35,
                            CorrectStreak = 0,
                            EngWordName = "meat",
                            IsKnown = false,
                            Picture = "C:/words/meat.jpg",
                            RepeatCount = 0,
                            TurWordName = "et"
                        },
                        new
                        {
                            WordID = 36,
                            CorrectStreak = 0,
                            EngWordName = "fish",
                            IsKnown = false,
                            Picture = "C:/words/fish.jpg",
                            RepeatCount = 0,
                            TurWordName = "balık"
                        },
                        new
                        {
                            WordID = 37,
                            CorrectStreak = 0,
                            EngWordName = "chicken",
                            IsKnown = false,
                            Picture = "C:/words/chicken.jpg",
                            RepeatCount = 0,
                            TurWordName = "tavuk"
                        },
                        new
                        {
                            WordID = 38,
                            CorrectStreak = 0,
                            EngWordName = "rice",
                            IsKnown = false,
                            Picture = "C:/words/rice.jpg",
                            RepeatCount = 0,
                            TurWordName = "pirinç"
                        },
                        new
                        {
                            WordID = 39,
                            CorrectStreak = 0,
                            EngWordName = "soup",
                            IsKnown = false,
                            Picture = "C:/words/soup.jpg",
                            RepeatCount = 0,
                            TurWordName = "çorba"
                        },
                        new
                        {
                            WordID = 40,
                            CorrectStreak = 0,
                            EngWordName = "salad",
                            IsKnown = false,
                            Picture = "C:/words/salad.jpg",
                            RepeatCount = 0,
                            TurWordName = "salata"
                        },
                        new
                        {
                            WordID = 41,
                            CorrectStreak = 0,
                            EngWordName = "orange",
                            IsKnown = false,
                            Picture = "C:/words/orange.jpg",
                            RepeatCount = 0,
                            TurWordName = "portakal"
                        },
                        new
                        {
                            WordID = 42,
                            CorrectStreak = 0,
                            EngWordName = "banana",
                            IsKnown = false,
                            Picture = "C:/words/banana.jpg",
                            RepeatCount = 0,
                            TurWordName = "muz"
                        },
                        new
                        {
                            WordID = 43,
                            CorrectStreak = 0,
                            EngWordName = "grape",
                            IsKnown = false,
                            Picture = "C:/words/grape.jpg",
                            RepeatCount = 0,
                            TurWordName = "üzüm"
                        },
                        new
                        {
                            WordID = 44,
                            CorrectStreak = 0,
                            EngWordName = "lemon",
                            IsKnown = false,
                            Picture = "C:/words/lemon.jpg",
                            RepeatCount = 0,
                            TurWordName = "limon"
                        },
                        new
                        {
                            WordID = 45,
                            CorrectStreak = 0,
                            EngWordName = "peach",
                            IsKnown = false,
                            Picture = "C:/words/peach.jpg",
                            RepeatCount = 0,
                            TurWordName = "şeftali"
                        },
                        new
                        {
                            WordID = 46,
                            CorrectStreak = 0,
                            EngWordName = "pear",
                            IsKnown = false,
                            Picture = "C:/words/pear.jpg",
                            RepeatCount = 0,
                            TurWordName = "armut"
                        },
                        new
                        {
                            WordID = 47,
                            CorrectStreak = 0,
                            EngWordName = "plum",
                            IsKnown = false,
                            Picture = "C:/words/plum.jpg",
                            RepeatCount = 0,
                            TurWordName = "erik"
                        },
                        new
                        {
                            WordID = 48,
                            CorrectStreak = 0,
                            EngWordName = "strawberry",
                            IsKnown = false,
                            Picture = "C:/words/strawberry.jpg",
                            RepeatCount = 0,
                            TurWordName = "çilek"
                        },
                        new
                        {
                            WordID = 49,
                            CorrectStreak = 0,
                            EngWordName = "cherry",
                            IsKnown = false,
                            Picture = "C:/words/cherry.jpg",
                            RepeatCount = 0,
                            TurWordName = "kiraz"
                        },
                        new
                        {
                            WordID = 50,
                            CorrectStreak = 0,
                            EngWordName = "melon",
                            IsKnown = false,
                            Picture = "C:/words/melon.jpg",
                            RepeatCount = 0,
                            TurWordName = "kavun"
                        },
                        new
                        {
                            WordID = 51,
                            CorrectStreak = 0,
                            EngWordName = "potato",
                            IsKnown = false,
                            Picture = "C:/words/potato.jpg",
                            RepeatCount = 0,
                            TurWordName = "patates"
                        },
                        new
                        {
                            WordID = 52,
                            CorrectStreak = 0,
                            EngWordName = "tomato",
                            IsKnown = false,
                            Picture = "C:/words/tomato.jpg",
                            RepeatCount = 0,
                            TurWordName = "domates"
                        },
                        new
                        {
                            WordID = 53,
                            CorrectStreak = 0,
                            EngWordName = "onion",
                            IsKnown = false,
                            Picture = "C:/words/onion.jpg",
                            RepeatCount = 0,
                            TurWordName = "soğan"
                        },
                        new
                        {
                            WordID = 54,
                            CorrectStreak = 0,
                            EngWordName = "garlic",
                            IsKnown = false,
                            Picture = "C:/words/garlic.jpg",
                            RepeatCount = 0,
                            TurWordName = "sarımsak"
                        },
                        new
                        {
                            WordID = 55,
                            CorrectStreak = 0,
                            EngWordName = "carrot",
                            IsKnown = false,
                            Picture = "C:/words/carrot.jpg",
                            RepeatCount = 0,
                            TurWordName = "havuç"
                        },
                        new
                        {
                            WordID = 56,
                            CorrectStreak = 0,
                            EngWordName = "cucumber",
                            IsKnown = false,
                            Picture = "C:/words/cucumber.jpg",
                            RepeatCount = 0,
                            TurWordName = "salatalık"
                        },
                        new
                        {
                            WordID = 57,
                            CorrectStreak = 0,
                            EngWordName = "pepper",
                            IsKnown = false,
                            Picture = "C:/words/pepper.jpg",
                            RepeatCount = 0,
                            TurWordName = "biber"
                        },
                        new
                        {
                            WordID = 58,
                            CorrectStreak = 0,
                            EngWordName = "eggplant",
                            IsKnown = false,
                            Picture = "C:/words/eggplant.jpg",
                            RepeatCount = 0,
                            TurWordName = "patlıcan"
                        },
                        new
                        {
                            WordID = 59,
                            CorrectStreak = 0,
                            EngWordName = "lettuce",
                            IsKnown = false,
                            Picture = "C:/words/lettuce.jpg",
                            RepeatCount = 0,
                            TurWordName = "marul"
                        },
                        new
                        {
                            WordID = 60,
                            CorrectStreak = 0,
                            EngWordName = "spinach",
                            IsKnown = false,
                            Picture = "C:/words/spinach.jpg",
                            RepeatCount = 0,
                            TurWordName = "ıspanak"
                        },
                        new
                        {
                            WordID = 61,
                            CorrectStreak = 0,
                            EngWordName = "broccoli",
                            IsKnown = false,
                            Picture = "C:/words/broccoli.jpg",
                            RepeatCount = 0,
                            TurWordName = "brokoli"
                        },
                        new
                        {
                            WordID = 62,
                            CorrectStreak = 0,
                            EngWordName = "cauliflower",
                            IsKnown = false,
                            Picture = "C:/words/cauliflower.jpg",
                            RepeatCount = 0,
                            TurWordName = "karnabahar"
                        },
                        new
                        {
                            WordID = 63,
                            CorrectStreak = 0,
                            EngWordName = "pumpkin",
                            IsKnown = false,
                            Picture = "C:/words/pumpkin.jpg",
                            RepeatCount = 0,
                            TurWordName = "balkabağı"
                        },
                        new
                        {
                            WordID = 64,
                            CorrectStreak = 0,
                            EngWordName = "corn",
                            IsKnown = false,
                            Picture = "C:/words/corn.jpg",
                            RepeatCount = 0,
                            TurWordName = "mısır"
                        },
                        new
                        {
                            WordID = 65,
                            CorrectStreak = 0,
                            EngWordName = "bean",
                            IsKnown = false,
                            Picture = "C:/words/bean.jpg",
                            RepeatCount = 0,
                            TurWordName = "fasulye"
                        },
                        new
                        {
                            WordID = 66,
                            CorrectStreak = 0,
                            EngWordName = "pea",
                            IsKnown = false,
                            Picture = "C:/words/pea.jpg",
                            RepeatCount = 0,
                            TurWordName = "bezelye"
                        },
                        new
                        {
                            WordID = 67,
                            CorrectStreak = 0,
                            EngWordName = "mushroom",
                            IsKnown = false,
                            Picture = "C:/words/mushroom.jpg",
                            RepeatCount = 0,
                            TurWordName = "mantar"
                        },
                        new
                        {
                            WordID = 68,
                            CorrectStreak = 0,
                            EngWordName = "olive",
                            IsKnown = false,
                            Picture = "C:/words/olive.jpg",
                            RepeatCount = 0,
                            TurWordName = "zeytin"
                        },
                        new
                        {
                            WordID = 69,
                            CorrectStreak = 0,
                            EngWordName = "honey",
                            IsKnown = false,
                            Picture = "C:/words/honey.jpg",
                            RepeatCount = 0,
                            TurWordName = "bal"
                        },
                        new
                        {
                            WordID = 70,
                            CorrectStreak = 0,
                            EngWordName = "jam",
                            IsKnown = false,
                            Picture = "C:/words/jam.jpg",
                            RepeatCount = 0,
                            TurWordName = "reçel"
                        },
                        new
                        {
                            WordID = 71,
                            CorrectStreak = 0,
                            EngWordName = "cake",
                            IsKnown = false,
                            Picture = "C:/words/cake.jpg",
                            RepeatCount = 0,
                            TurWordName = "pasta"
                        },
                        new
                        {
                            WordID = 72,
                            CorrectStreak = 0,
                            EngWordName = "pie",
                            IsKnown = false,
                            Picture = "C:/words/pie.jpg",
                            RepeatCount = 0,
                            TurWordName = "turta"
                        },
                        new
                        {
                            WordID = 73,
                            CorrectStreak = 0,
                            EngWordName = "cookie",
                            IsKnown = false,
                            Picture = "C:/words/cookie.jpg",
                            RepeatCount = 0,
                            TurWordName = "kurabiye"
                        },
                        new
                        {
                            WordID = 74,
                            CorrectStreak = 0,
                            EngWordName = "ice cream",
                            IsKnown = false,
                            Picture = "C:/words/icecream.jpg",
                            RepeatCount = 0,
                            TurWordName = "dondurma"
                        },
                        new
                        {
                            WordID = 75,
                            CorrectStreak = 0,
                            EngWordName = "juice",
                            IsKnown = false,
                            Picture = "C:/words/juice.jpg",
                            RepeatCount = 0,
                            TurWordName = "meyve suyu"
                        },
                        new
                        {
                            WordID = 76,
                            CorrectStreak = 0,
                            EngWordName = "tea",
                            IsKnown = false,
                            Picture = "C:/words/tea.jpg",
                            RepeatCount = 0,
                            TurWordName = "çay"
                        },
                        new
                        {
                            WordID = 77,
                            CorrectStreak = 0,
                            EngWordName = "coffee",
                            IsKnown = false,
                            Picture = "C:/words/coffee.jpg",
                            RepeatCount = 0,
                            TurWordName = "kahve"
                        },
                        new
                        {
                            WordID = 78,
                            CorrectStreak = 0,
                            EngWordName = "soda",
                            IsKnown = false,
                            Picture = "C:/words/soda.jpg",
                            RepeatCount = 0,
                            TurWordName = "soda"
                        },
                        new
                        {
                            WordID = 79,
                            CorrectStreak = 0,
                            EngWordName = "cola",
                            IsKnown = false,
                            Picture = "C:/words/cola.jpg",
                            RepeatCount = 0,
                            TurWordName = "kola"
                        },
                        new
                        {
                            WordID = 80,
                            CorrectStreak = 0,
                            EngWordName = "butcher",
                            IsKnown = false,
                            Picture = "C:/words/butcher.jpg",
                            RepeatCount = 0,
                            TurWordName = "kasap"
                        },
                        new
                        {
                            WordID = 81,
                            CorrectStreak = 0,
                            EngWordName = "baker",
                            IsKnown = false,
                            Picture = "C:/words/baker.jpg",
                            RepeatCount = 0,
                            TurWordName = "fırıncı"
                        },
                        new
                        {
                            WordID = 82,
                            CorrectStreak = 0,
                            EngWordName = "driver",
                            IsKnown = false,
                            Picture = "C:/words/driver.jpg",
                            RepeatCount = 0,
                            TurWordName = "şoför"
                        },
                        new
                        {
                            WordID = 83,
                            CorrectStreak = 0,
                            EngWordName = "teacher",
                            IsKnown = false,
                            Picture = "C:/words/teacher.jpg",
                            RepeatCount = 0,
                            TurWordName = "öğretmen"
                        },
                        new
                        {
                            WordID = 84,
                            CorrectStreak = 0,
                            EngWordName = "doctor",
                            IsKnown = false,
                            Picture = "C:/words/doctor.jpg",
                            RepeatCount = 0,
                            TurWordName = "doktor"
                        },
                        new
                        {
                            WordID = 85,
                            CorrectStreak = 0,
                            EngWordName = "nurse",
                            IsKnown = false,
                            Picture = "C:/words/nurse.jpg",
                            RepeatCount = 0,
                            TurWordName = "hemşire"
                        },
                        new
                        {
                            WordID = 86,
                            CorrectStreak = 0,
                            EngWordName = "police",
                            IsKnown = false,
                            Picture = "C:/words/police.jpg",
                            RepeatCount = 0,
                            TurWordName = "polis"
                        },
                        new
                        {
                            WordID = 87,
                            CorrectStreak = 0,
                            EngWordName = "fireman",
                            IsKnown = false,
                            Picture = "C:/words/fireman.jpg",
                            RepeatCount = 0,
                            TurWordName = "itfaiyeci"
                        },
                        new
                        {
                            WordID = 88,
                            CorrectStreak = 0,
                            EngWordName = "soldier",
                            IsKnown = false,
                            Picture = "C:/words/soldier.jpg",
                            RepeatCount = 0,
                            TurWordName = "asker"
                        },
                        new
                        {
                            WordID = 89,
                            CorrectStreak = 0,
                            EngWordName = "student",
                            IsKnown = false,
                            Picture = "C:/words/student.jpg",
                            RepeatCount = 0,
                            TurWordName = "öğrenci"
                        },
                        new
                        {
                            WordID = 90,
                            CorrectStreak = 0,
                            EngWordName = "engineer",
                            IsKnown = false,
                            Picture = "C:/words/engineer.jpg",
                            RepeatCount = 0,
                            TurWordName = "mühendis"
                        },
                        new
                        {
                            WordID = 91,
                            CorrectStreak = 0,
                            EngWordName = "lawyer",
                            IsKnown = false,
                            Picture = "C:/words/lawyer.jpg",
                            RepeatCount = 0,
                            TurWordName = "avukat"
                        },
                        new
                        {
                            WordID = 92,
                            CorrectStreak = 0,
                            EngWordName = "judge",
                            IsKnown = false,
                            Picture = "C:/words/judge.jpg",
                            RepeatCount = 0,
                            TurWordName = "hakim"
                        },
                        new
                        {
                            WordID = 93,
                            CorrectStreak = 0,
                            EngWordName = "pilot",
                            IsKnown = false,
                            Picture = "C:/words/pilot.jpg",
                            RepeatCount = 0,
                            TurWordName = "pilot"
                        },
                        new
                        {
                            WordID = 94,
                            CorrectStreak = 0,
                            EngWordName = "artist",
                            IsKnown = false,
                            Picture = "C:/words/artist.jpg",
                            RepeatCount = 0,
                            TurWordName = "sanatçı"
                        },
                        new
                        {
                            WordID = 95,
                            CorrectStreak = 0,
                            EngWordName = "actor",
                            IsKnown = false,
                            Picture = "C:/words/actor.jpg",
                            RepeatCount = 0,
                            TurWordName = "oyuncu"
                        },
                        new
                        {
                            WordID = 96,
                            CorrectStreak = 0,
                            EngWordName = "singer",
                            IsKnown = false,
                            Picture = "C:/words/singer.jpg",
                            RepeatCount = 0,
                            TurWordName = "şarkıcı"
                        },
                        new
                        {
                            WordID = 97,
                            CorrectStreak = 0,
                            EngWordName = "dancer",
                            IsKnown = false,
                            Picture = "C:/words/dancer.jpg",
                            RepeatCount = 0,
                            TurWordName = "dansçı"
                        },
                        new
                        {
                            WordID = 98,
                            CorrectStreak = 0,
                            EngWordName = "writer",
                            IsKnown = false,
                            Picture = "C:/words/writer.jpg",
                            RepeatCount = 0,
                            TurWordName = "yazar"
                        },
                        new
                        {
                            WordID = 99,
                            CorrectStreak = 0,
                            EngWordName = "poet",
                            IsKnown = false,
                            Picture = "C:/words/poet.jpg",
                            RepeatCount = 0,
                            TurWordName = "şair"
                        },
                        new
                        {
                            WordID = 100,
                            CorrectStreak = 0,
                            EngWordName = "scientist",
                            IsKnown = false,
                            Picture = "C:/words/scientist.jpg",
                            RepeatCount = 0,
                            TurWordName = "bilim insanı"
                        });
                });

            modelBuilder.Entity("WordApp.Models.WordSample", b =>
                {
                    b.Property<int>("WordSampleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WordSampleId"), 1L, 1);

                    b.Property<string>("Samples")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WordID")
                        .HasColumnType("int");

                    b.HasKey("WordSampleId");

                    b.HasIndex("WordID");

                    b.ToTable("WordSamples");
                });

            modelBuilder.Entity("WordApp.Models.WordSample", b =>
                {
                    b.HasOne("WordApp.Models.Word", "Word")
                        .WithMany("WordSamples")
                        .HasForeignKey("WordID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Word");
                });

            modelBuilder.Entity("WordApp.Models.Word", b =>
                {
                    b.Navigation("WordSamples");
                });
#pragma warning restore 612, 618
        }
    }
}
